TestCopyRespLoopConnectionError: Always ignore errors on stmt.Close()
Since recent versions of Go now report the error in Stmt.Close(), we
should not expect it to be nil.