Add Error.ErrorWithDetail() to print more details and position of errors (#1219)
Add a new ErrorWithDetail() method which also prints the Detail, Hint,
and query position (if any). For example:

    ERROR:  unacceptable schema name "pg_xx" (42939)
    DETAIL: The prefix "pg_" is reserved for system schemas.

Or if the Position is set and we have a query, or prints up to three
lines of context with a ^ to mark the position:

    ERROR:   invalid input syntax for type json (22P02)
    DETAIL:  Token "asd" is invalid.
    CONTEXT: line 5, column 8:

          3 | 'def',
          4 | 123,
          5 | 'foo', 'asd'::jsonb
                     ^

The format is based on what psql prints on errors (though not exactly
identical).

Based on the code I wrote for toml a few years ago:
https://github.com/BurntSushi/toml/blob/master/error.go

The regular error message now also includes the error code:

	pq: syntax error at end of input (42601)

psql doesn't print them, but I've found it useful on a number of
occasion, and I think in the context of a library like this it probably
makes sense.

Fixes #194
Fixes #521
Fixes #679
Fixes #895